# Generated by Django 6.0.1 on 2026-01-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
