# Generated by Django 6.0.1 on 2026-01-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_typingstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypingStatus',
        ),
    ]
